Demo/Demo/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('data_tables/', include('data_tables.urls')),
    path('tabulator_demo/', include('tabulator_demo.urls')),
	path('', index, name = 'index'),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Demo/apps/data_tables/urls.py
from . import views
from django.urls import path


app_name = 'data_tables'
urlpatterns = [
    path('get_data/', views.get_data, name = 'get_data'),
    path('', views.demo, name = 'demo'),
]

Demo/apps/tabulator_demo/urls.py
from . import views
from django.urls import path


app_name = 'tabulator_demo'
urlpatterns = [
    path('get_data/', views.get_data, name = 'get_data'),
    path('', views.demo, name = 'demo'),
]

Demo/apps/data_tables/models.py
from django.db import models

# Create your models here.

Demo/apps/tabulator_demo/models.py
from django.db import models

# Create your models here.

Demo/Demo/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html', locals())

Demo/apps/data_tables/views.py
from django.shortcuts import render
from django.http import HttpResponse
import json
from utils.test_data import TestData

# Create your views here.
def demo(request):
    return render(request, 'data_tables/demo.html', locals())


def get_data(request):
    data = TestData.get_json()
    return HttpResponse(json.dumps({"draw": 1, "recordsTotal": 57, "recordsFiltered": 57, 'data': data}))

Demo/apps/tabulator_demo/views.py
from django.shortcuts import render
from django.http import HttpResponse
import json
from utils.test_data import TestData

# Create your views here.
def demo(request):
    return render(request, 'tabulator_demo/demo.html', locals())

def get_data(request):
    data = json.dumps({"data" : TestData.get_json(), "last_page" : 1})
    return HttpResponse(data)

Demo/templates/base.html
<!DOCTYPE html>
<html>
<head>
{% block head %}
{% endblock %}
</head>
<body>
{% include 'menu.html' %}
{% block content %} {% endblock %}
{% include 'footer.html' %}
</body>
{% block js %} {% endblock %}
</html>

Demo/templates/data_tables/demo.html
{% extends 'base.html' %}
{% load static  %}
{% block head %}
{% include 'head.html' %}
<link rel="stylesheet" href='{% static "css/jquery.dataTables.min.css" %}' />
{% endblock %}

{% block content %}
<div class="tm-main uk-section uk-section-small">
    <div class="uk-container">
        <table id="example" class="display" style="width:100%">
            <thead>
                <tr>
                    <th>account_number</th>
                    <th>balance</th>
                    <th>firstname</th>
                    <th>lastname</th>
                    <th>age</th>
                    <th>gender</th>
                    <th>address</th>
                    <th>employer</th>
                    <th>email</th>
                    <th>city</th>
                    <th>state</th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <th>account_number</th>
                    <th>balance</th>
                    <th>firstname</th>
                    <th>lastname</th>
                    <th>age</th>
                    <th>gender</th>
                    <th>address</th>
                    <th>employer</th>
                    <th>email</th>
                    <th>city</th>
                    <th>state</th>
                </tr>
            </tfoot>
        </table>
    </div>
</div>
{% endblock %}

{% block js %}
{% include 'js.html' %}
<script src='{% static "js/jquery.dataTables.min.js" %}'></script>
<script src='{% static "js/ajax_csrf_token.js" %}'></script>
<script>
$(document).ready(function() {
    $('#example').DataTable({
        "bPaginate": false, //翻页功能
        "bInfo": false,//页脚信息
        "ordering": false, //不排序
        "searching": false,   //搜索框，不显示
        "bLengthChange": false, //改变每页显示数据数量，不显示
        "iDisplayLength": 10,    //每页默认显示数量（不显示了，这个设置也起不了作用）
        "serverSide":true,  //服务端
        "retrieve":false, //意思是如果已经初始化了，则继续使用之前的Datatables实例。
        "ajax": {
            "type": "GET",
			"url": "/data_tables/get_data",
			"dataSrc": function (result) {
                var json = JSON.parse(result).data;
                return json;
            }
		}
    });
});
</script>
{% endblock %}

Demo/templates/footer.html
<footer class="uk-text-center uk-margin-medium">2018 &copy; 云势软件</footer>

Demo/templates/head.html
{% load static  %}
<title>Demo</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href='{% static "css/uikit.min.css" %}'/>
<link rel="stylesheet" href='{% static "css/fontawesome-all.min.css" %}' />
<link rel="stylesheet" href='{% static "css/theme.css" %}' />
<link rel="stylesheet" href='{% static "css/metroStyle/metroStyle.css" %} '/>
<link rel="stylesheet" href='{% static "css/k_style.css" %}' />

Demo/templates/index.html
{% extends 'base.html' %}
{% block head %}
    {% include 'head.html' %}
{% endblock %}

{% block content %}
<div class="tm-main uk-section uk-section-small">
    <div class="uk-container">
    </div>
</div>
{% endblock %}

{% block js %}
    {% include 'js.html' %}
{% endblock %}

Demo/templates/js.html
{% load static  %}
<script src='{% static "js/uikit.min.js" %}'></script>
<script src='{% static "js/jquery-3.3.1.min.js" %}'></script>
<script src='{% static "js/jquery.ztree.all.min.js" %}'></script>
<script src='{% static "js/echarts.min.js" %}'></script>
<script src='{% static "js/macarons.js" %}'></script>
<script src='{% static "js/k_app.js" %}'></script>
<script src='{% static "js/k_tree.js" %}'></script>
<script src='{% static "js/uikit-icons.min.js" %}'></script>

Demo/templates/menu.html
<div uk-sticky="sel-target: .uk-navbar-container; cls-active: uk-navbar-sticky; bottom: #transparent-sticky-navbar">
    <nav class="uk-navbar-container tm-navbar-container" uk-navbar="mode: click">
        <div class="uk-navbar-left uk-margin-left">
            <a class="uk-navbar-item uk-logo" href="#">报表模板</a>
            <ul class="uk-navbar-nav">
                <li class="uk-active">
                    <a href="{% url 'data_tables:demo' %}">
                        <i class="fas fa-star uk-margin-small-right"></i>
                        <span>DataTables</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'tabulator_demo:demo' %}">
                        <i class="fas fa-star uk-margin-small-right"></i>
                        <span>Tabulator</span>
                    </a>
                </li>
                <li>
                    <a href="dm_report.html">
                        <i class="fas fa-star uk-margin-small-right"></i>
                        <span>Handsontable</span>
                    </a>
                </li>
            </ul>
        </div>
    </nav>
</div>

Demo/templates/tabulator_demo/demo.html
{% extends 'base.html' %}
{% load static  %}
{% block head %}
{% include 'head.html' %}
<link rel="stylesheet" href='{% static "css/tabulator.min.css" %}' />
{% endblock %}

{% block content %}
<div class="tm-main uk-section uk-section-small">
    <div class="uk-container">
        <div id="example-table"></div>
    </div>
</div>
{% endblock %}

{% block js %}
{% include 'js.html' %}
<script src='{% static "js/jquery-ui.min.js" %}'></script>
<script src='{% static "js/tabulator.min.js" %}'></script>
<script src='{% static "js/ajax_csrf_token.js" %}'></script>
<script>
$("#example-table").tabulator({
    height:"311px",
    layout:"fitColumns",
    ajaxURL:"/tabulator_demo/get_data",
    ajaxProgressiveLoad:"scroll",
    paginationSize:20,
    placeholder:"No Data Set",
    columns:[
        {title:"account_number", field:"account_number"},
    ],
});
</script>
{% endblock %}